// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orpgeekpghqejjddaehn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycGdlZWtwZ2hxZWpqZGRhZWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NDM1NjcsImV4cCI6MjA1MjQxOTU2N30.C1r7kCr8wz5w4P5jhu0lYRa3gq6RVcN4llpZcJkryWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);